# name: Hello Workflow

# on:
#   push:
#     branches:
#       - main

# jobs:
#   hello-job:

#     runs-on: ubuntu-latest

#     steps:

#       - name: Checkout Code
#         uses: actions/checkout@v4

#       - name: Print Hello
#         run: echo "Hello Maaz, GitHub Actions is working!"

#       - name: Show Current Directory
#         run: pwd

#       - name: List Files
#         run: ls -la

#       - name: Show Python Version
#         run: python --version



















